accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

base/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'base'

# URLパターンを登録する変数
urlpatterns = [
    # アプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),
    
    # 投稿ページへのアクセスはviewsモジュールのCreatePostViewを実行
    path('post/', views.CreatePostView.as_view(), name='post'),
    
    # 投稿完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    
    # カテゴリ一覧ページ
    # stock/<Categorysテーブルのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategoryViewに渡される
    path('stock/<int:category>',
         views.CategoryView.as_view(),
         name = 'post_cate'
         ),

    # ユーザーの投稿一覧ページ
    # stock/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user: id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name = 'user_list'
         ),
    
    # 詳細ページ
    # post-detail/<postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('post-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'post_detail'
         ),
    
    # マイページ
    # mypage/へのアクセスはMypageViewを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    # 投稿の削除
    # base/<postsテーブルのid値>/delete/にマッチング
    # <int:pk>は辞書{pk: id値(int)}としてDetailViewに渡される
    path('base/<int:pk>/delete/',
         views.DeleteView.as_view(),
         name = 'post_delete'
         ),
    # 問い合わせページのURLパターン
    path(
        # 問い合わせページのURLは「contact/」
        'contact/',
        # viewsモジュールのcontact_view()関数を実行
        views.contact_view,
        # URLパターンの名前を'contact'にする
        name='contact'
        ),
]

program/urls.py
from django.urls import path
from . import views

# URLconfのURLパターンを逆引きできるようにアプリ名を登録
app_name = 'program'

# URLパターンを登録するためのリスト
urlpatterns = [
    # http(s)://ホスト名/以下のパスが''(無し)の場合
    # viewsモジュールのselect_view()関数を実行
    # URLパターン名は'select'
    path('', views.select_view, name='select'),    
    
    #----------問題の出題ページ-------------------------------------------
    
    path(
        # 詳細ページのURLは「C-detail/レコードのid/」
        'c-program/<int:pk>/',
        # viewsモジュールのC_detail()関数を実行
        views.C_detail,
        # URLパターンの名前を'C_detail'にする
        name='C_detail'
        ),
    path(
        # 詳細ページのURLは「Python-detail/レコードのid/」
        'python-program/<int:pk>/',
        # viewsモジュールのPython_detail()関数を実行
        views.Python_detail,
        # URLパターンの名前を'Python_detail'にする
        name='Python_detail'
        ),
    path(
        # 詳細ページのURLは「Java-detail/レコードのid/」
        'java-program/<int:pk>/',
        # viewsモジュールのJava_detail()関数を実行
        views.Java_detail,
        # URLパターンの名前を'Java_detail'にする
        name='Java_detail'
        ),
    path(
        # 詳細ページのURLは「PHP-detail/レコードのid/」
        'Php-program/<int:pk>/',
        # viewsモジュールのPHP_detail()関数を実行
        views.Php_detail,
        # URLパターンの名前を'PHP_detail'にする
        name='Php_detail'
        ),
    path(
        # 詳細ページのURLは「Java-detail/レコードのid/」
        'Q-program/<int:pk>/',
        # viewsモジュールのJava_detail()関数を実行
        views.Q_detail,
        # URLパターンの名前を'Java_detail'にする
        name='Q_detail'
        ),
    path(
        # 詳細ページのURLは「Java-detail/レコードのid/」
        'py-program/<int:pk>/',
        # viewsモジュールのJava_detail()関数を実行
        views.py_detail,
        # URLパターンの名前を'Java_detail'にする
        name='py_detail'
        ),
    #----------問題の選択ページ-------------------------------------------
    
    path(
        # ページのURLは「learning/」
        'c-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.C_learning_view,
        # URLパターンの名前を'learning'にする
        name='C_list'
        ),
    path(
        # ページのURLは「learning/」
        'Python-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.Python_learning_view,
        # URLパターンの名前を'learning'にする
        name='Python_list'
        ),
    path(
        # ページのURLは「learning/」
        'Java-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.Java_learning_view,
        # URLパターンの名前を'learning'にする        
        name='Java_list'
        ),
    path(
        # ページのURLは「learning/」
        'Php-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.Php_learning_view,
        # URLパターンの名前を'learning'にする
        name='Php_list'
        ),
    path(
        # ページのURLは「learning/」
        'Q-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.Q_learning_view,
        # URLパターンの名前を'learning'にする
        name='Q_list'
        ),
    path(
        # ページのURLは「learning/」
        'py-list/',
        # viewsモジュールのlearning_view()関数を実行
        views.py_learning_view,
        # URLパターンの名前を'learning'にする
        name='py_list'
        ),
    #----------言語選択---------------------------------------------------
    
    path(
        # 問題の選択ページのURLは「select/」
        'select/',
        # viewsモジュールのselect_view()関数を実行
        views.select_view,
        # URLパターンの名前を'select'にする
        name='select'
        ),
]

project/urls.py
from django.contrib import admin
# include追加
from django.urls import path, include
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views
# settingsを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

# URLパターンを登録するための変数
urlpatterns = [
    path('admin/', admin.site.urls),
    
    # base.urlsへのURLパターン
    path('', include('base.urls')),
    
    # program.urlsへのURLパターン
    path('', include('program.urls')),
    
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),
    
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
   # MEDIA_URL = '/media/'
  settings.MEDIA_URL,
  # MEDIA_ROOTにリダイレクト
  document_root=settings.MEDIA_ROOT
  )

base/views.py
from django.shortcuts import render, redirect
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPostFormをインポート
from .forms import PostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからモデルPostをインポート
from .models import Post
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView
# formsモジュールからContactFormをインポート
from .forms import ContactForm
# django.contribからmesseagesをインポート
from django.contrib import messages
# django.core.mailモジュールからEmailMessageをインポート
from django.core.mail import EmailMessage

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = Post.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 6

# デコレーターにより、CreatePostViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name='dispatch')
class CreatePostView(CreateView):
    '''投稿ページのビュー
    
    PostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
      form_class: モデルとフィールドが登録されたフォームクラス
      template_name: レンダリングするテンプレート
      success_url: データベスへの登録完了後のリダイレクト先
    '''
    # forms.pyのPostFormをフォームクラスとして登録
    form_class = PostForm
    # レンダリングするテンプレート
    template_name = "post_content.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('base:post_done')

    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
          form(django.forms.Form):
            form_classに格納されているPostFormオブジェクト
        Return:
          HttpResponseRedirectオブジェクト:
            スーパークラスのform_valid()の戻り値を返すことで、
            success_urlで設定されているURLにリダイレクトさせる
        '''
        # commit=FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 投稿ユーザーのidを取得してモデルのuserフィールドに格納
        postdata.user = self.request.user
        # 投稿データをデータベースに登録
        postdata.save()
        # 戻り値はスーパークラスのform_valid()の戻り値(HttpResponseRedirect)
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    '''投稿完了ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name ='post_success.html'

class CategoryView(ListView):
    '''カテゴリページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 6

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''     
      # self.kwargsでキーワードの辞書を取得し、
      # categoryキーの値(Categorysテーブルのid)を取得
      category_id = self.kwargs['category']
      # filter(フィールド名=id)で絞り込む
      categories = Post.objects.filter(
        category=category_id).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return categories

class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 6

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      # self.kwargsでキーワードの辞書を取得し、
      # userキーの値(ユーザーテーブルのid)を取得
      user_id = self.kwargs['user']
      # filter(フィールド名=id)で絞り込む
      user_list = Post.objects.filter(
        user=user_id).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return user_list

class DetailView(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
     Attributes:
      template_name: レンダリングするテンプレート
      model: モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name ='detail.html'
    # クラス変数modelにモデルBlogPostを設定
    model = Post

class MypageView(ListView):
    '''マイページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # mypage.htmlをレンダリングする
    template_name ='mypage.html'
    # 1ページに表示するレコードの件数
    paginate_by = 6

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''
      # 現在ログインしているユーザー名はHttpRequest.userに格納されている
      # filter(userフィールド=userオブジェクト)で絞り込む
      queryset = Post.objects.filter(
        user=self.request.user).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return queryset
  
class DeleteView(DeleteView):
    '''レコードの削除を行うビュー
    
    Attributes:
      model: モデル
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
      success_url: 削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPostモデル
    model = Post
    # post_delete.htmlをレンダリングする
    template_name ='post_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('base:mypage')

    def delete(self, request, *args, **kwargs):
      '''レコードの削除を行う
      
      Parameters:
        self: DeleteViewオブジェクト
        request: WSGIRequest(HttpRequest)オブジェクト
        args: 引数として渡される辞書(dict)
        kwargs: キーワード付きの辞書(dict)
                {'pk': 21}のようにレコードのidが渡される
      
      Returns:
        HttpResponseRedirect(success_url)を返して
        success_urlにリダイレクト
      '''
      # スーパークラスのdelete()を実行
      return super().delete(request, *args, **kwargs)
  
def contact_view(request):
    '''Contactページのビュー    
    contact.htmlをレンダリングして戻り値として返す
    
    Parameters:
      request(HTTPRequest):
          クライアントからのリクエスト情報を格納したHTTPRequestオブジェクト
    
    Returns(HTTPResponse):
        Contactページへのアクセス時:
            render()でテンプレートをレンダリングした結果
        Sendボタンがクリックされた場合
            メールの送信処理完了後、Contactページにリダイレクトする
    '''
    # Contactページへのアクセスがあった場合(リクエストがGETの場合)
    # render()でテンプレートをレンダリングする
    if request.method == 'GET':
        # ContactFormオブジェクトを生成
        form = ContactForm()
        # render():
        # 第1引数: HTTPRequestオブジェクト
        # 第2引数: レンダリングするテンプレート
        # 第3引数: テンプレートに引き渡すdict型のデータ
        #         {キーは'form': ContactFormオブジェクト}
        return render(request, "contact.html", {'form': form})
    # 送信ボタン（Send)がクリックされた場合(リクエストがPOSTの場合)
    else:
        # ContactFormオブジェクトを生成(引数はPOSTされたフォームデータ)
        form = ContactForm(request.POST)
        # POSTされたフォームのデータがバリデーションを通過しているかを確認
        if form.is_valid():
            # フォームに入力されたデータをフィールド名を指定して取得
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            title = form.cleaned_data['title']
            message = form.cleaned_data['message']
            # メールのタイトルの書式を設定
            subject = 'お問い合わせ: {}'.format(title)
            # フォームの入力データの書式を設定
            message = \
              '送信者名: {0}\nメールアドレス: {1}\n タイトル:{2}\n メッセージ:\n{3}' \
              .format(name, email, title, message)
            # メールの送信元のアドレス(Gmail)
            from_email = 'sakaken2022@gmail.com'
            # 送信先のメールアドレス(Gmail)
            to_list = ['sakaken2022@gmail.com']
            # EmailMessageオブジェクトを生成
            message = EmailMessage(subject=subject,
                                   body=message,
                                   from_email=from_email,
                                   to=to_list,
                                   )
            # EmailMessageクラスのsend()でメールサーバーからメールを送信
            message.send()
            # 送信完了後に表示するメッセージ
            messages.success(
              request, 'お問い合わせありがとうございます。フォームは正常に送信されました。')
            # Contactページにリダイレクトする
            return redirect('base:contact')
        

    
    #return render(request, "'BASE_DIR/', program/learning.html", {'form': form})

base/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>Pro Learning</title>

    <!-- staticでfavicon.icoのURLを生成する -->
    <link rel="icon" type="image/x-icon"
　　        href={% static 'assets/favicon.ico' %} />
　　
    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できるプログラミング学習サイトです。
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Menu</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'base:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードリセット</a></li>
                <li><a href="{% url 'base:contact' %}"
                       class="text-white">Contact</a>
                </li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="{% url 'base:contact' %}"
                       class="text-white">Contact</a>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'base:index' %}"
             class="navbar-brand d-flex align-items-center">

            <!-- リンクテキスト-->
            <strong>Pro Learning</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>

    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'base:index' %}">Back to home</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          ©Takasaki University of Health and Welfare All rights reserved.</p>
      </div>
    </footer>

    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
  </body>
</html>

base/templates/post_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <!-- レコードが格納されたobject_listからレコードを1行ずつrecordに取り出す-->
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <!-- svgタグをimgに変更
                 src属性を追加して1枚目のイメージのURLを設定 -->
            {% if record.image1 %}
            <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
            </img>
            {% else %}
            <img src="/media/stock/noimage.png"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"></img>
            {% endif %}
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">
                <!-- titleフィールドを出力 -->
                {{record.title}}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <!-- 詳細ページを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'base:post_detail' record.pk %}'">
                          View</button>
                  <!-- カテゴリを表示するボタン -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'base:post_cate' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <!-- 投稿したユーザー名を出力-->
                <a href="{% url 'base:user_list' user=record.user.id %}">
                  <small class="text-muted">
                    {{record.user.username}}</small>
                </a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        <!-- forブロック終了 -->
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

base/templates/post_success.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Post Success{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br><br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>
          </div>
        </div>
      </div>
      {% endblock %}

base/templates/post_title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Pro Learning</h1>
        <p class="lead text-muted">
          言語を選んでプログラミング学習をはじめよう！</p>
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url 'program:select' %}"
             class="btn btn-primary my-2">学習</a>
          <a href="{% url 'accounts:logout' %}"
             class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}"
             class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
             class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>